[package]
name = "my_plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.29"
image = "0.25"    # For rendering images
imageproc = "0.25.0"
minifb = "0.27.0"
nalgebra = "0.30" # For handling data (optional)
rand = "0.8.5"    # For testing (optional)
rusttype = "0.9.3"


[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"
