[package]
name = "my_plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"    # For rendering images
nalgebra = "0.30" # For handling data (optional)
rand = "0.8.5"    # For testing (optional)


[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"
