name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install dependencies
      run: cargo fetch

    - name: Build each project
      run: |
        for dir in $(find . -type f -name "Cargo.toml" -exec dirname {} \;); do
          echo "Building project in $dir";
          (cd $dir && cargo build --verbose);
        done

    - name: Run tests for each project
      run: |
        for dir in $(find . -type f -name "Cargo.toml" -exec dirname {} \;); do
          echo "Running tests in $dir";
          (cd $dir && cargo test --verbose);
        done
